[package]
name = "wavs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
v8 = { git = "https://github.com/denoland/rusty_v8.git", tag = "v0.82.0" }
